M48
; DRILL file KiCad 10.0.6 date 2026-09-27T20:55:05
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-27T20:55:05+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X14.32Y40.5
T2
X15.0Y47.5
M30
