// Generated by firmware/tools/design_filters.py - do not edit.
// A-weighting after CIC-4/R=64 at fs = 23437.5 S/s, coefficients Q13.
// Worst deviation from IEC 61672 A, 50 Hz - 8 kHz, after quantisation: 0.01 dB.
#pragma once
#define FILT_Q 13
#define FS_OUT_X2 46875   // 2 x output sample rate (46875)
// first-order high-pass poles (A-weighting real poles [20.6, 20.6, 107.7, 737.9] Hz), Q13
#define HP_P0 8147
#define HP_P1 8147
#define HP_P2 7959
#define HP_P3 6722
// correction biquad: y = (B0 x + B1 x1 + B2 x2 - A1 y1 - A2 y2) >> Q
#define BQ_B0 12909
#define BQ_B1 10972
#define BQ_B2 775
#define BQ_A1 10687
#define BQ_A2 3151
