#!/usr/bin/env python3
"""Design the A-weighting chain for dbfob and write ../src/filters.h.

Signal path (firmware/src/dsp.c):
  PDM 1.5 MHz -> CIC order 4, R=64 -> 23,437.5 S/s
              -> 4 first-order high-pass sections: the A-weighting's real poles at
                 20.6 (x2), 107.7 and 737.9 Hz, each with its zero at DC (matched z)
              -> 1 biquad fitted to what is left: the 12,194 Hz pole pair (above Nyquist),
                 the CIC droop, and the matched-z error
Fixed point: coefficients Q13 so that every product of a <=17-bit sample fits in int32, and
all of them are compile-time constants (the V003 has no multiplier; GCC turns a multiply
by a constant into shifts and adds). The quantised response is checked here against the
IEC 61672 A curve; the C implementation is checked against this by test_dsp.py.
"""
import numpy as np, os, sys
from scipy.optimize import least_squares

FS_IN = 1_500_000
R, N = 64, 4
FS = FS_IN / R                          # 23,437.5 S/s
Q = 13
HERE = os.path.dirname(os.path.abspath(__file__))


def a_weight_db(f):
    f = np.asarray(f, float)
    ra = (12194.0**2 * f**4) / ((f**2 + 20.6**2) * np.sqrt((f**2 + 107.7**2) * (f**2 + 737.9**2)) * (f**2 + 12194.0**2))
    return 20 * np.log10(ra) + 2.00


def cic_db(f):
    x = np.pi * np.asarray(f, float) / FS_IN
    return 20 * N * np.log10(np.abs(np.sin(R * x) / (R * np.sin(x))))


def hp1_resp(p, f):
    z = np.exp(1j * 2 * np.pi * f / FS)
    return (1 - 1 / z) / (1 - p / z)


def biquad_resp(b, a, f):
    z1 = np.exp(-1j * 2 * np.pi * f / FS)
    return (b[0] + b[1] * z1 + b[2] * z1**2) / (1 + a[0] * z1 + a[1] * z1**2)


POLES_HZ = [20.6, 20.6, 107.7, 737.9]


def chain_db(p_list, b, a, f):
    h = np.ones_like(f, dtype=complex)
    for p in p_list: h *= hp1_resp(p, f)
    h *= biquad_resp(b, a, f)
    return 20 * np.log10(np.abs(h)) + cic_db(f)


def design():
    p = [np.exp(-2 * np.pi * fc / FS) for fc in POLES_HZ]
    pq = [round(x * 2**Q) / 2**Q for x in p]
    f = np.geomspace(50, 10000, 400)
    target = a_weight_db(f)
    base = chain_db(pq, [1, 0, 0], [0, 0], f)
    w = np.where(f <= 8000, 1.0, 0.3)          # fit hardest where club energy is

    def err(v):
        b, a = v[:3], v[3:]
        r = np.roots([1, a[0], a[1]])
        pen = np.maximum(np.abs(r) - 0.95, 0).sum() * 100      # keep the poles well inside
        return np.append(w * (base + 20 * np.log10(np.abs(biquad_resp(b, a, f))) - target), pen)
    v = least_squares(err, [1, 0.5, 0.1, -0.2, 0.05]).x
    b, a = v[:3], v[3:]
    bq = [round(x * 2**Q) / 2**Q for x in b]
    aq = [round(x * 2**Q) / 2**Q for x in a]
    return p, pq, bq, aq


def main():
    p, pq, bq, aq = design()
    f = np.array([20, 31.5, 50, 63, 100, 125, 250, 500, 1000, 2000, 4000, 6300, 8000, 10000], float)
    got = chain_db(pq, bq, aq, f)
    print(f"fs = {FS} S/s   Q{Q}")
    print(" f/Hz    A(f)   chain   error")
    worst = 0
    for fi, g, t in zip(f, got, a_weight_db(f)):
        print(f"{fi:7.1f} {t:7.2f} {g:7.2f} {g - t:+6.2f}")
        if 50 <= fi <= 8000: worst = max(worst, abs(g - t))
    print(f"worst |error| 50 Hz - 8 kHz: {worst:.2f} dB")
    ints = lambda xs: [int(round(x * 2**Q)) for x in xs]
    hdr = os.path.join(HERE, '..', 'src', 'filters.h')
    with open(hdr, 'w') as fh:
        fh.write(f"""// Generated by firmware/tools/design_filters.py - do not edit.
// A-weighting after CIC-{N}/R={R} at fs = {FS} S/s, coefficients Q{Q}.
// Worst deviation from IEC 61672 A, 50 Hz - 8 kHz, after quantisation: {worst:.2f} dB.
#pragma once
#define FILT_Q {Q}
#define FS_OUT_X2 {int(FS * 2)}   // 2 x output sample rate (46875)
// first-order high-pass poles (A-weighting real poles {POLES_HZ} Hz), Q{Q}
#define HP_P0 {ints(pq)[0]}
#define HP_P1 {ints(pq)[1]}
#define HP_P2 {ints(pq)[2]}
#define HP_P3 {ints(pq)[3]}
// correction biquad: y = (B0 x + B1 x1 + B2 x2 - A1 y1 - A2 y2) >> Q
#define BQ_B0 {ints(bq)[0]}
#define BQ_B1 {ints(bq)[1]}
#define BQ_B2 {ints(bq)[2]}
#define BQ_A1 {ints(aq)[0]}
#define BQ_A2 {ints(aq)[1]}
""")
    print('wrote', os.path.normpath(hdr))
    write_cic_tables()
    return worst


def write_cic_tables():
    """Byte-step tables for the order-4 CIC in dsp.c: Wk[b] = sum over set bits j (x0 = MSB, first
    in time) of C(8 - j + k - 2, k - 1). const, so they live in flash, not in the V003's 2 KB RAM."""
    w = {1: [], 2: [], 3: [], 4: []}
    for b in range(256):
        acc = {1: 0, 2: 0, 3: 0, 4: 0}
        for j in range(8):
            if b & (0x80 >> j):
                n = 8 - j
                acc[1] += 1; acc[2] += n; acc[3] += n * (n + 1) // 2; acc[4] += n * (n + 1) * (n + 2) // 6
        for k in w: w[k].append(acc[k])
    rows = lambda xs: ',\n\t'.join(', '.join(str(v) for v in xs[i:i + 16]) for i in range(0, 256, 16))
    hdr = os.path.join(HERE, '..', 'src', 'cic_tables.h')
    with open(hdr, 'w') as fh:
        fh.write('// Generated by firmware/tools/design_filters.py - do not edit.\n'
                 '// Order-4 CIC byte-step tables, see dsp.c.\n#pragma once\n#include <stdint.h>\n')
        for k, t in (('1', 'uint8_t'), ('2', 'uint8_t'), ('3', 'uint8_t'), ('4', 'uint16_t')):
            fh.write(f'static const {t} W{k}[256] = {{\n\t{rows(w[int(k)])}\n}};\n')
    sq = [i * i for i in range(511)]
    with open(hdr, 'a') as fh:
        fh.write('// Squares 0..510 for the table multiply in dsp.c (the V003 has no multiplier).\n'
                 f'static const uint32_t SQ[511] = {{\n\t{",\n\t".join(", ".join(str(v) for v in sq[i:i + 12]) for i in range(0, 511, 12))}\n}};\n')
    print('wrote', os.path.normpath(hdr))


if __name__ == '__main__':
    sys.exit(0 if main() < 1.0 else 1)
